import { UserRole } from "src/user/enum/role.enum";


export interface JwtPayload {
  sub: string; // userId
  email: string; // user's email
  role: UserRole; // user's role
  iat?: number; // issued at (auto-generated by JWT)
  exp?: number; // expiration time (auto-generated by JWT)
}
